### ISSUE TITLE
Infinite loop when transferring time entries to Clockify

### ISSUE THREAD

**Issue by mikerourke** [mikerourke/toggl-to-clockify#10]
## Description
When running the `toggl-to-clockify transfer` command, the time entry transfer portion would continue running even though entries weren't being created

## Source
User emailed me with error details

## Steps to Reproduce
1. Ensure configuration files is present (run `toggl-to-clockify init`)
2. Ensure the workspaces field in the configuration file is populated with valid values
3. Run `toggl-to-clockify transfer`

**Comment by mikerourke** [comment]
The bug was being caused by an incorrect payload for new Clockify projects. I added a temporary fix and merged it in #11, but I need to address the following issues:
- API request errors aren't being handled (> `400` is being swallowed)
- Estimate details from Toggl project need to be passed to the Clockify project
  - Right now, just setting estimate to `0` and type to `MANUAL`

**Comment by Lucatiel641** [comment]
Hey, Mike, how's the progress with this bug? This is still happening with me (the entries keep going forever), can you help me? Thanks!

**Comment by matheuslimacs** [comment]
Hey Mike, mine's creating infinite entries apparently, does this qualify as this infinite loop bug? It's currently at entry 6000. Can you help me? Thanks!

**Comment by mikerourke** [comment]
@Lucatiel641 I'll try to take a look at it tonight. I'm traveling abroad for work right now so my availability is a little limited. I'm actually currently working on a web app version that's about 85% done. I'm planning on archiving this repo when it's complete. If you want to hold off on the transfer for a week or two, I'll send you the link to the app when it's ready.

**Comment by matheuslimacs** [comment]
No problem @mikerourke , take your time, and thank you! :)

**Comment by Lotrax** [comment]
> Hey Mike, mine's creating infinite entries apparently, does this qualify as this infinite loop bug? It's currently at entry 6000. Can you help me? Thanks!

Same here. Have restarted it but the same thing happens and no data is written into Clockify.

**Comment by mikerourke** [comment]
@Lotrax I apologize for the delayed response, it's been a hectic few days at work. So I'm about 95% done with a web app that I'm going to host on surge.sh (or some variant of that) that allows you to transfer the stuff through a UI. I think I addressed the infinite loop issues in the new codebase.

I've been bogged down with work for the last few weeks, but I'm aiming to have it ready by the first or second week of February. Would you mind waiting a couple of weeks to transfer? I wanted to have it ready last week but got slammed at my job. Here's the repo btw: https://github.com/mikerourke/toggl-to-clockify-web

**Comment by Lotrax** [comment]
@mikerourke Thank you for your response. No need to apologize, I appreciate your efforts for this tool. The reason I responded is that I wasn't sure if an update had been pushed, and if it had, the problem still came up. No problem for me to wait, good luck with your efforts and I'll see the update ;) 

Have a good day, cheers.

**Comment by favad1** [comment]
Hey! @mikerourke  - did you get some time to work on it? Its a great service that you are doing. Thanks

**Comment by mikerourke** [comment]
@favad1 I'll finally have some time this week! I can patch this library to get it working again. I'll let you know when it's ready.

**Comment by favad1** [comment]
Sounds good. very much appreciated. We're waiting on you to fix this - before we can move our 8 people in 3 work-spaces to Clockify. Thank You

**Comment by mikerourke** [comment]
@favad1 So transferring multiple users in a workspace is going to be tricky. Enough people have requested this feature, so I'm working on it now. I'm focusing most of my efforts on the web version though. I've got some time this weekend to work on it, but it's going to take a little bit of time. Most of the functionality is there, but setting up the workflow properly and testing it will be challenging. I'll let you know when it's ready.

**Comment by vesper8** [comment]
Just tried using this promising tool to transfer my girlfriend's Toggl data for a single workspace, all from 2019. I followed the instructions to the letter.. got api keys from both sides, created a new workspace on Clockify with the same one-word name as on Toggl. Added the year (2019 only) and ran the transfer.

It just entered what seemed like an infinite loop and didn't create anything on Clockify's side

So I assume I'm running into the same issue.. is there a workaround? Is a fix right around the corner? @mikerourke Thank you for your contribution through this project

**Comment by vesper8** [comment]
Ok so after some tinkering I was able to get it going. Here's what I did:

First of all, my girlfriend had not created any clients and her projects were not associated to any client. She only had created a workspace and a few projects

I created a client, then associated her projects with that client.

Unfortunately I don't know if this alone is what allowed the transfer to go through. Because I had a hunch that one other thing might be causing a problem. One of the project names was in Spanish and had one of those accents on the letter 'o'. I know how stingy some scripts can be with accents, so I renamed it without the accent.

I then ran the transfer again and this time it completed successfully, importing projects and clients and all time entries

Hope this helps you reproduce and fix what was happening! Cheers!

**Comment by mikerourke** [comment]
@vesper8 OMG! Thank you so much, I was just looking dejectedly through all my code trying to figure out why it was working for me and not for you. I'll take a look at the client code and implement a fix. You're the best!!!

**Comment by mikerourke** [comment]
Sometimes programming sucks, it's not all Lamborghinis and lavish parties like the papers say.

**Comment by Coimbra1984** [comment]
Hi,

I guess I hit the same problem. I'm not sure whether this PR is already in the npm package.
I installed it as suggested with
npm install -g toggl-to-clockify
But I'm ending up in an endless loop. Next I tried to install the package from github directly with
npm install -g https://github.com/mikerourke/toggl-to-clockify.git

But then I ended up with this:
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/toggl-to-clockify/lib/cmds'

**Comment by mikerourke** [comment]
I’m actually at the tail end of finishing up the web version of this tool (I’ll be deprecating this library in the next week or so). I’ll include you on the list of people to inform when it’s ready.

**Comment by Coimbra1984** [comment]
Okay, thanks. If the web sources are hosted on github and you need any help, just tell me.

**Comment by hernanpuente** [comment]
> I’m actually at the tail end of finishing up the web version of this tool (I’ll be deprecating this library in the next week or so). I’ll include you on the list of people to inform when it’s ready.

Hey @mikerourke, could you please add me to that list as well? I had the same infinite loop issue when trying to use your tool, so I am not waiting for the new web version. Thanks!

**Comment by mikerourke** [comment]
@hernanpuente Absolutely! I got the initial time entry transfer code working on Monday. I need to add a few more things, then it’s ready to publish. I’ll send you the link when it’s ready.

**Comment by hernanpuente** [comment]
Because you rock!
