### ISSUE TITLE
Import Toggl clients

### ISSUE THREAD

**Issue by consulthys** [mikerourke/toggl-to-clockify#2]
Before creating a new project in Clockify, it'd be nice to also import clients from Toggl, so that projects can be linked to clients (via [`toggleProject.cid`](https://github.com/mikerourke/toggl-to-clockify/blob/d27a2e9de2f494eaffb5ff4ddd28d576c9ece850/src/tools/Clockify.ts#L248))

**Comment by mikerourke** [comment]
That should be feasible. I could add a flag for the command like `--clients-only` or something along those lines.

**Comment by mikerourke** [comment]
Whoops, I initially misunderstood this. I need to add Toggl clients to Clockify, get ID, then ensure the Clockify project has the corresponding client.

**Comment by consulthys** [comment]
It works like a charm with your latest commit f2c84a34beefe28a823306cc6351e50b7761735f
Thanks a lot!
